{
 "title": "Internet/Bandwidth Monitor",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "isp", "label": "ISP", "query": "speed_detail" },
   { "name": "ip_address", "label": "IP Address", "query": "speed_detail" },
   { "name": "server", "label": "Server", "query": "speed_detail" }
  ]
 },
 "panels": [
  {
   "title": "Download",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "targets": [
    { "expr": "speed_download_bandwidth" }
   ]
  },
  {
   "title": "Latency",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    { "expr": "speed_ping_latency" }
   ]
  },
  {
   "title": "Ping",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "ping_aws_amazon_com", "legendFormat": "aws.amazon.com" },
    { "expr": "ping_cloudflare_com", "legendFormat": "cloudflare.com" },
    { "expr": "ping_google_com", "legendFormat": "google.com" }
   ]
  },
  {
   "title": "Upload",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "targets": [
    { "expr": "speed_upload_bandwidth" }
   ]
  },
  {
   "title": "Jitter",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 6 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    { "expr": "speed_ping_jitter" }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "loss_aws_amazon_com", "legendFormat": "aws.amazon.com" },
    { "expr": "loss_cloudflare_com", "legendFormat": "cloudflare.com" },
    { "expr": "loss_google_com", "legendFormat": "google.com" }
   ]
  }
 ]
}