version: '3.2'

networks: 
    monitor:
        driver: bridge

services: 

    prometheus:
        image: prom/prometheus
        ports:
            - 9090:9090
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        networks: 
            - monitor

    grafana:
        image: grafana/grafana
        ports:
            - 3000:3000
        volumes: 
            - ./provisioning/:/etc/grafana/provisioning/
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=secret
        networks: 
            - monitor

    redis:
        image: redis:latest
        command: ["redis-server", "--appendonly", "yes"]
        ports: 
            - "6379:6379"
        networks: 
            - monitor

    app:
        build: 
            context: ./
            dockerfile: ./Dockerfile
        ports: 
            - "80:${METRICS_PORT}"
        networks: 
            - monitor
        env_file: 
            - .env